// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StudentInfoDemo.Models;

#nullable disable

namespace StudentInfoDemo.Migrations
{
    [DbContext(typeof(StudentInfoDbContext))]
    [Migration("20261007101442_Third")]
    partial class Third
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StudentInfoDemo.Models.Student", b =>
                {
                    b.Property<int>("sid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("stuid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("sid"));

                    b.Property<string>("adhaar")
                        .HasColumnType("varchar(12)")
                        .HasColumnName("stuadhaar");

                    b.Property<DateOnly>("dob")
                        .HasColumnType("date")
                        .HasColumnName("studob");

                    b.Property<string>("email")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("stuemail");

                    b.Property<string>("gender")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("stugen");

                    b.Property<string>("name")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("stuname");

                    b.Property<string>("phone")
                        .HasColumnType("varchar(100)")
                        .HasColumnName("stuphone");

                    b.HasKey("sid");

                    b.ToTable("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
